version: "3.9"

services:
  agent:
    build:
      context: .
      target: agent
    env_file: .env
    restart: unless-stopped
    network_mode: host

  dashboard:
    build:
      context: .
      target: dashboard
    ports:
      - "8080:8080"
    env_file: .env
    restart: unless-stopped
